# fly.toml app configuration file generated for todo-llm-db on 2025-05-05T23:19:42-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todo-llm-db'
primary_region = 'sea'

[build]
  [build.args]
    NEXT_PUBLIC_EXAMPLE = 'Value goes here'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
