packages:
  - nextjs-starter
  - nodejs-typescript-basic
  - svelte-starter
  - nuxt-starter
  - nextjs-pdf-example
  - nodejs-mcp-server
  - form-filler
  - json-schema-to-baml
  - node-aws-lambda-sst
