# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..clients.client_gpt4client import GPT4Client
from ..functions.fx_answerprompt import BAMLAnswerPrompt
from baml_lib._impl.deserializer import Deserializer


# Impl: v1
# Client: GPT4Client
# An implementation of .


__prompt_template = """\
Given the following information, answer the query in 2 to 5 sentences

    Information: {info}

    Query: {query}

    Output:\
"""

__input_replacers = {
    "{info}",
    "{query}"
}


# We ignore the type here because baml does some type magic to make this work
# for inline SpecialForms like Optional, Union, List.
__deserializer = Deserializer[str](str)  # type: ignore

@BAMLAnswerPrompt.register_impl("v1")
async def v1(*, info: str, query: str) -> str:
    response = await GPT4Client.run_prompt_template(template=__prompt_template, replacers=__input_replacers, params=dict(info=info, query=query))
    return __deserializer.from_string(response.generated)
