# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..clients.client_gpt4client import GPT4Client
from ..functions.fx_clarifyprompt import BAMLClarifyPrompt
from baml_lib._impl.deserializer import Deserializer


# Impl: v1
# Client: GPT4Client
# An implementation of .


__prompt_template = """\
Answer the following clarification query appropriately given the response the query is about. The information the response was generated from is also provided.

    Prompt: {query}

    Response: {response}

    Information: {info}

    Output:\
"""

__input_replacers = {
    "{info}",
    "{query}",
    "{response}"
}


# We ignore the type here because baml does some type magic to make this work
# for inline SpecialForms like Optional, Union, List.
__deserializer = Deserializer[str](str)  # type: ignore

@BAMLClarifyPrompt.register_impl("v1")
async def v1(*, query: str, response: str, info: str) -> str:
    response = await GPT4Client.run_prompt_template(template=__prompt_template, replacers=__input_replacers, params=dict(query=query, response=response, info=info))
    return __deserializer.from_string(response.generated)
