[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "baml-py==0.207.1",
    "fastapi>=0.115.12",
    "pydantic>=2.11.4",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
