/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Check, Checked  } from "../types";
import type { Image, Audio } from "@boundaryml/baml";

import type {  Answer,  BookAnalysis,  CharacterDescription,  Citation,  ClassWithBlockDone,  ClassWithoutDone,  Context,  Document,  Education,  Experience,  Guide,  Ingredient,  Link,  Message,  PartIngredient,  PartSteps,  Person,  PopularityOverTime,  Query,  Ranking,  Recipe,  Reply,  Resume,  Score,  SemanticContainer,  SmallThing,  Spells,  Tweet,  Van,  VanSideAnalysis,  VehicleSideResponse,  Visibility,  WordCount,  Category,  ReplyType,  Role,  VehicleSide } from "../types"

import type * as types from "../types"
import type { partial_types }from "../partial_types";

export type StreamingServerTypes = {
  AnswerQuestion: partial_types.Answer,
  ExtractResumeNoStructure: string,
  GenerateGuide: partial_types.Guide,
  IsResume: boolean,
  ExtractResume: partial_types.Resume,
  AnalyzeBooks: partial_types.BookAnalysis,
  ClassifyMessage: (Category | null)[],
  GenerateReplies: (partial_types.Reply | null)[],
  ExtractPerson: partial_types.Person,
  DescribeCharacter: partial_types.CharacterDescription,
  GetRecipe: partial_types.Recipe,
  IdentifyVehicleSide: partial_types.VehicleSideResponse,
  MakeSemanticContainer: partial_types.SemanticContainer,
  AnalyzeVanSide: partial_types.VanSideAnalysis,
}