/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
'use server'

import { b } from '../index';
import type { Check, Checked  } from "../types";
import type { Image, Audio } from "@boundaryml/baml";

import type {  Answer,  BookAnalysis,  CharacterDescription,  Citation,  ClassWithBlockDone,  ClassWithoutDone,  Context,  Document,  Education,  Experience,  Guide,  Ingredient,  Link,  Message,  PartIngredient,  PartSteps,  Person,  PopularityOverTime,  Query,  Ranking,  Recipe,  Reply,  Resume,  Score,  SemanticContainer,  SmallThing,  Spells,  Tweet,  Van,  VanSideAnalysis,  VehicleSideResponse,  Visibility,  WordCount,  Category,  ReplyType,  Role,  VehicleSide } from "../types"

import type * as types from "../types"

/**
 * Streaming BAML server actions that return ReadableStreams.
 */

/**
 * Executes the streaming variant of the "AnalyzeBooks" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } input - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeBooks = async (
  input: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeBooks(
    input,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnalyzeVanSide" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } vanImage - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnalyzeVanSide = async (
  vanImage: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnalyzeVanSide(
    vanImage,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "AnswerQuestion" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } question - Input parameter.
 * @param { Context } context - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const AnswerQuestion = async (
  question: string,
  context: Context,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.AnswerQuestion(
    question,
    context,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "ClassifyMessage" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Message[] } convo - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const ClassifyMessage = async (
  convo: Message[],
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.ClassifyMessage(
    convo,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "DescribeCharacter" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } first_image - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const DescribeCharacter = async (
  first_image: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.DescribeCharacter(
    first_image,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "ExtractPerson" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } input - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const ExtractPerson = async (
  input: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.ExtractPerson(
    input,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "ExtractResume" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } raw_text - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const ExtractResume = async (
  raw_text: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.ExtractResume(
    raw_text,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "ExtractResumeNoStructure" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } raw_text - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const ExtractResumeNoStructure = async (
  raw_text: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.ExtractResumeNoStructure(
    raw_text,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "GenerateGuide" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } arg - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const GenerateGuide = async (
  arg: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.GenerateGuide(
    arg,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "GenerateReplies" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Tweet[] } tweets - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const GenerateReplies = async (
  tweets: Tweet[],
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.GenerateReplies(
    tweets,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "GetRecipe" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } arg - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const GetRecipe = async (
  arg: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.GetRecipe(
    arg,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "IdentifyVehicleSide" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { Image } vanImage - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const IdentifyVehicleSide = async (
  vanImage: Image,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.IdentifyVehicleSide(
    vanImage,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "IsResume" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 * @param { string } raw_text - Input parameter.
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const IsResume = async (
  raw_text: string,
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.IsResume(
    raw_text,
  );
  return Promise.resolve(stream.toStreamable());
};

/**
 * Executes the streaming variant of the "MakeSemanticContainer" BAML action.
 *
 * This action initiates a streaming response by calling the corresponding
 * BAML stream function. The returned stream yields incremental updates.
 *
 *
 * @returns {ReadableStream<Uint8Array>} A stream that yields incremental updates from the action.
 */
export const MakeSemanticContainer = async (
): Promise<ReadableStream<Uint8Array>> => {
  const stream = b.stream.MakeSemanticContainer(
  );
  return Promise.resolve(stream.toStreamable());
};