/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Check, Checked  } from "../types";
import type { Image, Audio } from "@boundaryml/baml";

import type {  AddItem,  AdjustItem,  Answer,  BookAnalysis,  Category,  CharacterDescription,  Citation,  ClassWithBlockDone,  ClassWithoutDone,  Context,  Document,  Education,  Experience,  GetDateTime,  Guide,  Ingredient,  Link,  Message,  MessageToUser,  PartIngredient,  PartSteps,  Person,  PopularityOverTime,  Query,  Ranking,  Recipe,  Reply,  ReplyType,  Resume,  Role,  Score,  SemanticContainer,  SmallThing,  Spells,  State,  Tag,  TodoItem,  TodoList,  TodoQuery,  ToolCallResult,  Tweet,  Van,  VanSideAnalysis,  VehicleSide,  VehicleSideResponse,  Visibility,  WordCount } from "../types"

import type * as types from "../types"
import type { partial_types }from "../partial_types";

export type StreamingServerTypes = {
  AnalyzeBooks: partial_types.BookAnalysis,
  AnalyzeVanSide: partial_types.VanSideAnalysis,
  AnswerQuestion: partial_types.Answer,
  ClassifyMessage: (Category | null)[],
  DescribeCharacter: partial_types.CharacterDescription,
  ExtractPerson: partial_types.Person,
  ExtractResume: partial_types.Resume,
  ExtractResumeNoStructure: string,
  GenerateGuide: partial_types.Guide,
  GenerateReplies: (partial_types.Reply | null)[],
  GetRecipe: partial_types.Recipe,
  IdentifyVehicleSide: partial_types.VehicleSideResponse,
  IsResume: boolean,
  MakeSemanticContainer: partial_types.SemanticContainer,
  SelectTools: ((partial_types.MessageToUser | null) | (types.AddItem | null) | (types.AdjustItem | null) | null)[],
}