###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Generic, List, Optional, TypeVar, Union
import pprint

import baml_py
from pydantic import BaseModel, ValidationError, create_model

from . import partial_types, types

OutputType = TypeVar('OutputType')

def coerce(cls: BaseModel, parsed: Any) -> Any:
  try:
    return cls.model_validate({"inner": parsed}).inner
  except ValidationError as e:
    raise TypeError(
      "Internal BAML error while casting output to {}\n{}".format(
        cls.__name__,
        pprint.pformat(parsed)
      )
    ) from e

class BamlClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager)

    @property
    def stream(self):
      return self.__stream_client

    
    async def ClassifyMessage(
        self,
        convo: List[types.Message]
    ) -> List[types.Category]:
      raw = await self.__runtime.call_function(
        "ClassifyMessage",
        {
          "convo": convo,
        },
        self.__ctx_manager.get(),
      )
      mdl = create_model("ClassifyMessageReturnType", inner=(List[types.Category], ...))
      return coerce(mdl, raw.parsed())
    
    async def ExtractResume(
        self,
        raw_text: str
    ) -> types.Resume:
      raw = await self.__runtime.call_function(
        "ExtractResume",
        {
          "raw_text": raw_text,
        },
        self.__ctx_manager.get(),
      )
      mdl = create_model("ExtractResumeReturnType", inner=(types.Resume, ...))
      return coerce(mdl, raw.parsed())
    

class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    def ClassifyMessage(
        self,
        convo: List[types.Message]
    ) -> baml_py.BamlStream[List[Optional[types.Category]], List[types.Category]]:
      raw = self.__runtime.stream_function(
        "ClassifyMessage",
        {
          "convo": convo,
        },
        None,
        self.__ctx_manager.get(),
      )

      mdl = create_model("ClassifyMessageReturnType", inner=(List[types.Category], ...))
      partial_mdl = create_model("ClassifyMessagePartialReturnType", inner=(List[Optional[types.Category]], ...))


      return baml_py.BamlStream[List[Optional[types.Category]], List[types.Category]](
        raw,
        lambda x: coerce(partial_mdl, x),
        lambda x: coerce(mdl, x),
        self.__ctx_manager.get(),
      )
    
    def ExtractResume(
        self,
        raw_text: str
    ) -> baml_py.BamlStream[partial_types.Resume, types.Resume]:
      raw = self.__runtime.stream_function(
        "ExtractResume",
        {
          "raw_text": raw_text,
        },
        None,
        self.__ctx_manager.get(),
      )

      mdl = create_model("ExtractResumeReturnType", inner=(types.Resume, ...))
      partial_mdl = create_model("ExtractResumePartialReturnType", inner=(partial_types.Resume, ...))


      return baml_py.BamlStream[partial_types.Resume, types.Resume](
        raw,
        lambda x: coerce(partial_mdl, x),
        lambda x: coerce(mdl, x),
        self.__ctx_manager.get(),
      )
    