###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel
from typing import List, Optional, Union

from . import types

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################


class Education(BaseModel):
    school: Optional[str]
    degree: Optional[str]
    year: Optional[int]

class Message(BaseModel):
    role: Optional[types.Role]
    content: Optional[str]

class Resume(BaseModel):
    name: Optional[str]
    education: List["Education"]
    skills: List[Optional[str]]
