# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.
#
# BAML version: 0.1.1-canary.12
# Generated Date: __DATE__
# Generated by: __USER__

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from baml_lib._impl.functions import BaseBAMLFunction
from typing import List, Protocol, runtime_checkable


IClarifyPromptOutput = str

@runtime_checkable
class IClarifyPrompt(Protocol):
    """
    This is the interface for a function.

    Args:
        query: str
        response: List[str]

    Returns:
        str
    """

    async def __call__(self, *, query: str, response: List[str]) -> str:
        ...


class IBAMLClarifyPrompt(BaseBAMLFunction[str]):
    def __init__(self) -> None:
        super().__init__(
            "ClarifyPrompt",
            IClarifyPrompt,
            ["v1"],
        )

BAMLClarifyPrompt = IBAMLClarifyPrompt()

__all__ = [ "BAMLClarifyPrompt" ]
