# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from baml_lib._impl.functions import BaseBAMLFunction
from typing import Protocol, runtime_checkable


IClarifyPromptOutput = str

@runtime_checkable
class IClarifyPrompt(Protocol):
    """
    This is the interface for a function.

    Args:
        query: str
        response: str
        info: str

    Returns:
        str
    """

    async def __call__(self, *, query: str, response: str, info: str) -> str:
        ...


class IBAMLClarifyPrompt(BaseBAMLFunction[str]):
    def __init__(self) -> None:
        super().__init__(
            "ClarifyPrompt",
            IClarifyPrompt,
            ["v1"],
        )

BAMLClarifyPrompt = IBAMLClarifyPrompt()

__all__ = [ "BAMLClarifyPrompt" ]
