# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..types.enums.enm_classifyprompt import ClassifyPrompt
from baml_lib._impl.functions import BaseBAMLFunction
from typing import Protocol, runtime_checkable


IPromptTypeOutput = ClassifyPrompt

@runtime_checkable
class IPromptType(Protocol):
    """
    This is the interface for a function.

    Args:
        arg: str

    Returns:
        ClassifyPrompt
    """

    async def __call__(self, arg: str, /) -> ClassifyPrompt:
        ...


class IBAMLPromptType(BaseBAMLFunction[ClassifyPrompt]):
    def __init__(self) -> None:
        super().__init__(
            "PromptType",
            IPromptType,
            ["v1"],
        )

BAMLPromptType = IBAMLPromptType()

__all__ = [ "BAMLPromptType" ]
