# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..types.classes.cls_attendee import Attendee
from ..types.classes.cls_audience import Audience
from ..types.classes.cls_thing import Thing
from typing import Protocol, runtime_checkable


import typing

import pytest
from contextlib import contextmanager
from unittest import mock

ImplName = typing.Literal["simple"]

T = typing.TypeVar("T", bound=typing.Callable[..., typing.Any])
CLS = typing.TypeVar("CLS", bound=type)


IThingyOutput = str

@runtime_checkable
class IThingy(Protocol):
    """
    This is the interface for a function.

    Args:
        arg: Audience

    Returns:
        str
    """

    async def __call__(self, arg: Audience, /) -> str:
        ...


class BAMLThingyImpl:
    async def run(self, arg: Audience, /) -> str:
        ...

class IBAMLThingy:
    def register_impl(
        self, name: ImplName
    ) -> typing.Callable[[IThingy], IThingy]:
        ...

    async def __call__(self, arg: Audience, /) -> str:
        ...

    def get_impl(self, name: ImplName) -> BAMLThingyImpl:
        ...

    @contextmanager
    def mock(self) -> typing.Generator[mock.AsyncMock, None, None]:
        """
        Utility for mocking the ThingyInterface.

        Usage:
            ```python
            # All implementations are mocked.

            async def test_logic() -> None:
                with baml.Thingy.mock() as mocked:
                    mocked.return_value = ...
                    result = await ThingyImpl(...)
                    assert mocked.called
            ```
        """
        ...

    @typing.overload
    def test(self, test_function: T) -> T:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the ThingyInterface.

        Args:
            test_function : T
                The test function to be decorated.

        Usage:
            ```python
            # All implementations will be tested.

            @baml.Thingy.test
            async def test_logic(ThingyImpl: IThingy) -> None:
                result = await ThingyImpl(...)
            ```
        """
        ...

    @typing.overload
    def test(self, *, exclude_impl: typing.Iterable[ImplName]) -> pytest.MarkDecorator:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the ThingyInterface.

        Args:
            exclude_impl : Iterable[ImplName]
                The names of the implementations to exclude from testing.

        Usage:
            ```python
            # All implementations except "simple" will be tested.

            @baml.Thingy.test(exclude_impl=["simple"])
            async def test_logic(ThingyImpl: IThingy) -> None:
                result = await ThingyImpl(...)
            ```
        """
        ...

    @typing.overload
    def test(self, test_class: typing.Type[CLS]) -> typing.Type[CLS]:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the ThingyInterface.

        Args:
            test_class : Type[CLS]
                The test class to be decorated.

        Usage:
        ```python
        # All implementations will be tested in every test method.

        @baml.Thingy.test
        class TestClass:
            def test_a(self, ThingyImpl: IThingy) -> None:
                ...
            def test_b(self, ThingyImpl: IThingy) -> None:
                ...
        ```
        """
        ...

BAMLThingy: IBAMLThingy
