[project]
name = "survey-answerer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "baml-py>=0.78.0",
    "pydantic>=2.10.6",
    "python-dotenv>=1.0.1",
]
