# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..types.classes.cls_attendee import Attendee
from ..types.classes.cls_conversation import Conversation
from ..types.classes.cls_meetingrequest import MeetingRequest
from ..types.classes.cls_message import Message
from ..types.enums.enm_usertype import UserType
from ..types.partial.classes.cls_attendee import PartialAttendee
from ..types.partial.classes.cls_conversation import PartialConversation
from ..types.partial.classes.cls_meetingrequest import PartialMeetingRequest
from ..types.partial.classes.cls_message import PartialMessage
from baml_core.stream import AsyncStream
from typing import Callable, Protocol, runtime_checkable


import typing

import pytest
from contextlib import contextmanager
from unittest import mock

ImplName = typing.Literal["simple"]

T = typing.TypeVar("T", bound=typing.Callable[..., typing.Any])
CLS = typing.TypeVar("CLS", bound=type)


IExtractMeetingRequestInfoOutput = MeetingRequest

@runtime_checkable
class IExtractMeetingRequestInfo(Protocol):
    """
    This is the interface for a function.

    Args:
        convo: Conversation
        now: str

    Returns:
        MeetingRequest
    """

    async def __call__(self, *, convo: Conversation, now: str) -> MeetingRequest:
        ...

   

@runtime_checkable
class IExtractMeetingRequestInfoStream(Protocol):
    """
    This is the interface for a stream function.

    Args:
        convo: Conversation
        now: str

    Returns:
        AsyncStream[MeetingRequest, PartialMeetingRequest]
    """

    def __call__(self, *, convo: Conversation, now: str
) -> AsyncStream[MeetingRequest, PartialMeetingRequest]:
        ...
class BAMLExtractMeetingRequestInfoImpl:
    async def run(self, *, convo: Conversation, now: str) -> MeetingRequest:
        ...
    
    def stream(self, *, convo: Conversation, now: str
) -> AsyncStream[MeetingRequest, PartialMeetingRequest]:
        ...

class IBAMLExtractMeetingRequestInfo:
    def register_impl(
        self, name: ImplName
    ) -> typing.Callable[[IExtractMeetingRequestInfo, IExtractMeetingRequestInfoStream], None]:
        ...

    async def __call__(self, *, convo: Conversation, now: str) -> MeetingRequest:
        ...

    def stream(self, *, convo: Conversation, now: str
) -> AsyncStream[MeetingRequest, PartialMeetingRequest]:
        ...

    def get_impl(self, name: ImplName) -> BAMLExtractMeetingRequestInfoImpl:
        ...

    @contextmanager
    def mock(self) -> typing.Generator[mock.AsyncMock, None, None]:
        """
        Utility for mocking the ExtractMeetingRequestInfoInterface.

        Usage:
            ```python
            # All implementations are mocked.

            async def test_logic() -> None:
                with baml.ExtractMeetingRequestInfo.mock() as mocked:
                    mocked.return_value = ...
                    result = await ExtractMeetingRequestInfoImpl(...)
                    assert mocked.called
            ```
        """
        ...

    @typing.overload
    def test(self, test_function: T) -> T:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the ExtractMeetingRequestInfoInterface.

        Args:
            test_function : T
                The test function to be decorated.

        Usage:
            ```python
            # All implementations will be tested.

            @baml.ExtractMeetingRequestInfo.test
            async def test_logic(ExtractMeetingRequestInfoImpl: IExtractMeetingRequestInfo) -> None:
                result = await ExtractMeetingRequestInfoImpl(...)
            ```
        """
        ...

    @typing.overload
    def test(self, *, exclude_impl: typing.Iterable[ImplName] = [], stream: bool = False) -> pytest.MarkDecorator:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the ExtractMeetingRequestInfoInterface.

        Args:
            exclude_impl : Iterable[ImplName]
                The names of the implementations to exclude from testing.
            stream: bool
                If set, will return a streamable version of the test function.

        Usage:
            ```python
            # All implementations except the given impl will be tested.

            @baml.ExtractMeetingRequestInfo.test(exclude_impl=["implname"])
            async def test_logic(ExtractMeetingRequestInfoImpl: IExtractMeetingRequestInfo) -> None:
                result = await ExtractMeetingRequestInfoImpl(...)
            ```

            ```python
            # Streamable version of the test function.

            @baml.ExtractMeetingRequestInfo.test(stream=True)
            async def test_logic(ExtractMeetingRequestInfoImpl: IExtractMeetingRequestInfoStream) -> None:
                async for result in ExtractMeetingRequestInfoImpl(...):
                    ...
            ```
        """
        ...

    @typing.overload
    def test(self, test_class: typing.Type[CLS]) -> typing.Type[CLS]:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the ExtractMeetingRequestInfoInterface.

        Args:
            test_class : Type[CLS]
                The test class to be decorated.

        Usage:
        ```python
        # All implementations will be tested in every test method.

        @baml.ExtractMeetingRequestInfo.test
        class TestClass:
            def test_a(self, ExtractMeetingRequestInfoImpl: IExtractMeetingRequestInfo) -> None:
                ...
            def test_b(self, ExtractMeetingRequestInfoImpl: IExtractMeetingRequestInfo) -> None:
                ...
        ```
        """
        ...

BAMLExtractMeetingRequestInfo: IBAMLExtractMeetingRequestInfo
