# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.
#
# BAML version: 0.1.1-canary.12
# Generated Date: __DATE__
# Generated by: __USER__

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from .clients.client_gpt35client import GPT35Client
from .clients.client_gpt4client import GPT4Client
from .functions.fx_answerprompt import BAMLAnswerPrompt
from .functions.fx_clarifyprompt import BAMLClarifyPrompt
from .functions.fx_prompttype import BAMLPromptType


from baml_lib import baml_init 
class BAMLClient:
    AnswerPrompt = BAMLAnswerPrompt
    ClarifyPrompt = BAMLClarifyPrompt
    PromptType = BAMLPromptType
    GPT35Client = GPT35Client
    GPT4Client = GPT4Client

    def __init__(self):
        baml_init()

baml = BAMLClient()
