/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import { Image } from "@boundaryml/baml"
export enum Category {
  Refund = "Refund",
  CancelOrder = "CancelOrder",
  TechnicalSupport = "TechnicalSupport",
  AccountIssue = "AccountIssue",
  Question = "Question",
}

export enum ReplyType {
  HUMOROUS = "HUMOROUS",
  SARCASTIC = "SARCASTIC",
  CURIOUS = "CURIOUS",
  INTELLECTUAL = "INTELLECTUAL",
}

export enum Role {
  Customer = "Customer",
  Assistant = "Assistant",
}

export interface Answer {
  answersInText: Citation[]
  answer: string
  
}

export interface BookAnalysis {
  bookNames: string[]
  popularityOverTime: PopularityOverTime[]
  popularityRankings: Ranking[]
  wordCounts: WordCount[]
  
}

export interface CharacterDescription {
  name: string
  clothingItems: string[]
  hairColor?: string | null
  smellDescription: string
  spells: Spells[]
  
}

export interface Citation {
  number: number
  documentTitle: string
  sourceLink: string
  relevantTextFromDocument: string
  
}

export interface Context {
  documents: Document[]
  
}

export interface Document {
  title: string
  text: string
  link: string
  
}

export interface Education {
  school: string
  degree: string
  year: number
  
}

export interface Experience {
  company: string
  title?: string | null
  start_date: string
  end_date?: string | null
  description: string[]
  company_url?: string | null
  
}

export interface Ingredient {
  name: string
  amount: number
  unit: string
  description?: string | null
  
}

export interface Link {
  url: Checked<string,"valid_link">
  
}

export interface Message {
  role: Role
  content: string
  
}

export interface PartIngredient {
  title: string
  ingredients: Ingredient[]
  
}

export interface PartSteps {
  title: string
  steps: string[]
  
}

export interface Person {
  
  [key: string]: any;
}

export interface PopularityOverTime {
  bookName: string
  scores: Score[]
  
}

export interface Ranking {
  bookName: string
  score: number
  
}

export interface Recipe {
  topic: "food" | "other"
  number_of_servings: number
  ingredients: PartIngredient[] | Ingredient[]
  instructions: PartSteps[] | string[]
  serving_tips: string[]
  
}

export interface Reply {
  reply_text: string
  reply_type: ReplyType
  
}

export interface Resume {
  name: string
  links: Link[]
  education: Education[]
  experience: Experience[]
  skills: string[]
  why_hire: string[]
  
}

export interface Score {
  year: number
  score: number
  
}

export interface Spells {
  name: string
  description: string
  
}

export interface Tweet {
  user: string
  text: string
  
}

export interface WordCount {
  bookName: string
  count: number
  
}
