/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
/* eslint-disable */
import { Image } from "@boundaryml/baml"
export enum Category {
  Refund = "Refund",
  CancelOrder = "CancelOrder",
  TechnicalSupport = "TechnicalSupport",
  AccountIssue = "AccountIssue",
  Question = "Question",
}

export enum Role {
  Customer = "Customer",
  Assistant = "Assistant",
}

export interface Education {
  school: string
  degree: string
  year: number
  
}

export interface Message {
  role: Role
  content: string
  
}

export interface Resume {
  name: string
  education: Education[]
  skills: string[]
  
}
